language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

install:
  - sudo pip install coverage

script: phpunit ./tests --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
dist: trusty 
  
