language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  
cache:
  directories:
  - cldr
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
  
script: phpunit ./tests

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coverage
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
  
